### ISSUE TITLE
Release tag and support for homebrew

### ISSUE THREAD

**Issue by yhu266** [ctrlcctrlv/TT2020#11]
I'd like to add homebrew support for this font. It'll make it more convenient for macOS users to install/update this font.

Could the author set up a release tag? A versioned on would be the best.

**Comment by ctrlcctrlv** [comment]
I am honored that you enjoy my font to the degree that you want to redistribute it. 

However I am a bit confused as to your intention. Do you wish to build the font every time before you install it? I would strongly caution against doing so. Building this font requires hours and hours of CPU time to generate all of the glyphs ten times for all of the styles at a very high DPI, and then to trace them. 

It is my understanding that Homebrew is for building software. Or do you simply want me to tag a release so that you can distribute my TTFs? This, I recommend.

**Comment by ctrlcctrlv** [comment]
(If you have a GPU and GPU-enabled GIMP the build time can be cut substantially but still it takes around ten minutes. This is a massive font.)

**Comment by yhu266** [comment]
Similar to what I did with another font, see https://github.com/Homebrew/homebrew-cask-fonts/blob/master/Casks/font-atkinson-hyperlegible.rb for an example.

Basically, that file redistributes your font without building. A release tag (of TTFs) will be very helpful.

**Comment by yhu266** [comment]
It will automate the installing procedure for macOS users, and if your have a versioned tag, it'll update itself automatically as well.

**Comment by ctrlcctrlv** [comment]
Okay that's good yes I will tag a release. 

actually I have a bug that is simple to fix, will take 5 minutes, but I have been putting it off so I will fix that also and make a real release right now.

**Comment by yhu266** [comment]
Thank you!

**Comment by yhu266** [comment]
Thank you for the release! Is is possible for `TT2020` to have separated asset files (zip) for fonts, like you did with https://github.com/ctrlcctrlv/chomsky/releases/tag/v2.1 and https://github.com/ctrlcctrlv/some-time-later/releases/tag/v3.2 ?

**Comment by yhu266** [comment]
The current release style will work for sure.

**Comment by ctrlcctrlv** [comment]
Due to the giant size of this font, no. Also, I'm about to finish 0.2.1, you might want to wait five minutes~

**Comment by ctrlcctrlv** [comment]
Pushed
