### ISSUE TITLE
Regular and italic versions of certain styles can't be used simultaneously on Windows

### ISSUE THREAD

**Issue by Fussmatte** [ctrlcctrlv/TT2020#15]
When I installed the fonts, it installed the Italic versions first, and I was unable to use it as a Regular, non-Italic font in those specific styles (Base, B, D, E). After uninstalling and reinstalling individually, the Regular styles first, trying to italicise text in those styles will not use the special Italic styles, but will instead simply slant the font as if there wasn't an Italic version installed.

**Comment by ctrlcctrlv** [comment]
I'll investigate. Could be a problem of font metadata. Thanks. I plan to make a new release soon, so I will investigate this as part of that 1.0 release

**Comment by ctrlcctrlv** [comment]
Thanks to @kencmd, I now know that this issue is related to #18. Because #18 has more info on how to fix it, even though this issue is older, I'm closing it in favor of #18. Thanks for your report. Fixing this is high up on my list of things to do next year, this year was the year of FRB American Cursive I'm afraid, there's only one of me :blush:

**Comment by ctrlcctrlv** [comment]
(I meant to write "thanks to @kenmcd" above.)
