### ISSUE TITLE
Italic Styles overwrite the Normal styles of font style B and E

### ISSUE THREAD

**Issue by ZeroDayOwl** [ctrlcctrlv/TT2020#21]
On my system, I installed both the Regular and Italic versions of Font Style B and E. After installing the fonts, only the Italic versions of B and E appeared in my word processor, not the Regular version. Although in my `Personalization` tab, I saw that I had both versions of each font installed.

However, only if I uninstall the Italic versions, the Regular version becomes available. Is there any way to make both the version of each style available on editors?

**Comment by kenmcd** [comment]
This is caused by the Italics fonts having the style-group set to Bold.
Which causes confusion in applications when trying to use the fonts. 
This has been reported previously: https://github.com/ctrlcctrlv/TT2020/issues/15 https://github.com/ctrlcctrlv/TT2020/issues/18
Thought this would have been fixed by now.

Here are some fixed fonts - try these: 
[TT2020.Fixed.Names.Base.and.B.only.zip](https://github.com/ctrlcctrlv/TT2020/files/9507956/TT2020.Fixed.Names.Base.and.B.only.zip)
[TT2020.Fixed.Names.D.and.E.only.zip](https://github.com/ctrlcctrlv/TT2020/files/9507960/TT2020.Fixed.Names.D.and.E.only.zip)
(had to put it in 2 separate ZIPs to get around the 10MB file size limit)

The F and G fonts should work as is.

**Comment by ZeroDayOwl** [comment]
Thanks a lot @kenmcd! Those fonts work well on my system.

Hope the dev would fix the issue in the style-group of the Italics fonts and upload the fixed font files on the repo.

**Comment by ctrlcctrlv** [comment]
Are you OK with that @kenmcd? I don't mind uploading your patched fonts for people to use in the meantime as #18 needs more time to be solved.

**Comment by ctrlcctrlv** [comment]
If you consent please open a PR or else write this in a message:

> I consent to have my edited TT2020 fonts be committed by Fredrick Brennan (@ctrlcctrlv) and release them under the same license as TT2020, *id est*, the SIL Open Font License v1.1.

**Comment by kenmcd** [comment]
> If you consent please open a PR or else write this in a message:
> 
> > I consent to have my edited TT2020 fonts be committed by Fredrick Brennan (@ctrlcctrlv) and release them under the same license as TT2020, _id est_, the SIL Open Font License v1.1.

Yes, I consent to the above.
What ever you want to do with them is OK with me.
Happy to contribute.

@ZeroDayOwl  Glad they are working now.
I did not test them extensively.
So you are now the official tester.
Let me (us) know if you have any other issues.

**Comment by ZeroDayOwl** [comment]
Thank you @kenmcd for your contribution and @ctrlcctrlv for uploading the patched fonts.

So far, the fonts are working well on my system.
I will let you know if I face any issues using them on other applications.

Cheerios!
