### ISSUE TITLE
version without ligatures?

### ISSUE THREAD

**Issue by andy-goryachev** [ctrlcctrlv/TT2020#8]
This is a great font, excellent work!

Would it be possible to create a version without ligatures (ex.: "fi", "fl")?  It is rather strange to see ligatures in a typewriter-style font.

See it on Mac as well as Win 10.

Thank you.
-andy

**Comment by andy-goryachev** [comment]
![image](https://user-images.githubusercontent.com/5430849/72659243-7e396600-3971-11ea-8d2c-ca7283e77b1a.png)

**Comment by andy-goryachev** [comment]
[ligatures.zip](https://github.com/ctrlcctrlv/TT2020/files/4080016/ligatures.zip)

**Comment by andy-goryachev** [comment]
"typewriters"...

**Comment by ctrlcctrlv** [comment]
For now, you can disable ligatures on a per-application basis. 

Unfortunately, some of those applications might _also_ disable the `calt` feature which is where the alternates live. Nothing I can do about that, `kitty` was one such application until I contributed a patch to fix it. (See kovidgoyal/kitty#2247.)

In the next release I will probably move the ligatures into `dlig` (discretionary ligatures), which applications don't enable by default, unless I think of a better solution first.

By the way, sorry to ask because your name is Russian sounding, but does the Cyrillic in the italic look OK to you?

**Comment by andy-goryachev** [comment]
The application is MS Word in Win10 (and TextEdit on Mac, but my target is Word).  Do you know how to disable ligatures there?

I haven't looked at italic Cyrillic specifically.  I can take a look though - which file should I download?

**Comment by ctrlcctrlv** [comment]
>  Do you know how to disable ligatures there?

No, but I'm sure it's possible.

Any of the italic fonts should have it.

**Comment by andy-goryachev** [comment]
Alas, I don't know how to disable ligatures in Word.

As for the italic Cyrillic (installed t2020 base italic ttf) - it looks rather unusual.  I mean, it is not without a certain character and charm - it is not a hand written style, at least not the kind of canonical style that was taught in elementary schools in the 70s, but it is certainly has a right to live.

I would, hovewer, change a few things: "б" (lowercase BE U+0431) looks rather weird, and "ы" (U+044b) looks like a glitch of some kind.

ъ (U+044a) and ь (U+044c) also look weird.

Hope this helps.

P.S.  I am neither a typographer nor a designer.

**Comment by ctrlcctrlv** [comment]
Sorry for the eleven month delay, I fixed this :)

`dlig` is now in use.

**Comment by andy-goryachev** [comment]
+1
thanks!
